### PR TITLE
adding place layer changes

### PR DESCRIPTION
**Pull request by mmc1718**
Copying place layer changes from https://github.com/onthegomap/planetiler/commit/a857ef021145130adc5312425d43953428c2d2c5

### CODE REVIEW

**Comment by nmr8acme** [comment]
Was it planetiler-openmaptiles and onthegomap/planetiler that had unrelated git histories?

Does planetiler-openmaptiles use planetiler as a dependency?

If so, why does this change need to be applied in both repos?

**Comment by mmc1718** [comment]
> Was it planetiler-openmaptiles and onthegomap/planetiler that had unrelated git histories?
Yes

> Does planetiler-openmaptiles use planetiler as a dependency?
Yes

> If so, why does this change need to be applied in both repos?
It is not possible to keep this change in the current Planetiler repo if we want to ever update it - i.e. after updating, this change will no longer be there. This is because the changed files have been removed and are now only found in planetiler-openmaptiles.

Using the most up to date Planetiler ensures that any potential changes to the raw planet.osm.pbf schema or breaking changes in other dependencies will be taken into account.

**Comment by nmr8acme** [comment]
Gotcha. 

So was this change made in onthegomap/planetiler, and then some earlier part of onthegomap/planetiler was carved off to form planetiler-openmaptiles? And then after this change, the carved out part was deleted?

**Comment by mmc1718** [comment]
Yes. Or rather it was a change made in nmr8acme/planetiler, but the corresponding files in onthegomap/planetiler were deleted

**Comment by nmr8acme** [comment]
Ohhhhh, got it. The link you posted https://github.com/onthegomap/planetiler/commit/a857ef021145130adc5312425d43953428c2d2c5 was for the parent repo so I assumed that commit was in there, but it looks like it may just be found in nmr8acme/planetiler

**Comment by mmc1718** [comment]
Ah sorry, I had without realising navigated away from our fork onto the main repo for a while and must have copied the link from there before I realised I was in the wrong repo. Yes, the changes are just in the fork :)

**Pull request merged**
